### ISSUE TITLE
Error at early init on Chrome

### ISSUE THREAD

**Issue by pakal** [jcblw/zoomy-plugin#11]
Tried with jquery 1.7 and 1.9.1 (the latter with jquery-migrate), with today's trunk code of zoomy

If on Chrome I keep the mouse on the image when it loads, I get an error "TypeError: Cannot read property 'half' of undefined".

The JS line concerned is that one : posX        = utils.pos.mouse(e.pageX, l.left , dataset.size.half),

On firefox all is fine. It seems there is a moment when zoomy isnt fully initialized and callbacks already registered fail badly.

Good luck and thx for the cool plugin.

**Comment by jcblw** [comment]
Interesting bug, I was attaching events to Zoomy before the large image was loaded, but adding those parameters that the events depend on after the image load hence the missing data. I think its because of the behavior in which chrome loads the images. 

In my repo's example, I have three images all the large images just scaled down. Firefox and alot of other browsers would load the whole data once. Where chrome will try to load a smaller image first, I assume to be faster. I guess this would also be the case with two images anyways.

Nice catch!
